/**
 * Output safety (illustrative, sanitized).
 *
 * Three output-side defenses:
 *   1. white-label scrub — strip vendor/platform brand names so output ships
 *      under the CLIENT's brand;
 *   2. prompt-leak detection — catch internal system text before it reaches
 *      a user;
 *   3. fail-closed HTML allowlist — only known-safe markup survives, so a
 *      model can't introduce stored XSS into a served page.
 */

/* ---------------------------------------------------------------- *
 * 1. White-label scrub
 * ---------------------------------------------------------------- */

// Representative list; the production set is configuration-driven.
const VENDOR_NAMES = [
  "BlixNex",
  "OpenRouter",
  "DeepSeek",
  "Anthropic",
  "Claude",
  "OpenAI",
];

const POWERED_BY = /\b(powered by|built with|generated by)\b[^.<\n]*/gi;

export function scrubVendorNames(text: string, clientBrand: string): string {
  let out = text.replace(POWERED_BY, "");
  for (const name of VENDOR_NAMES) {
    out = out.replace(new RegExp(`\\b${escapeRegExp(name)}\\b`, "gi"), clientBrand);
  }
  return out;
}

/* ---------------------------------------------------------------- *
 * 2. Prompt-leak detection
 * ---------------------------------------------------------------- */

const LEAK_SIGNATURES = [
  /\[SOURCE-OF-TRUTH RULES\]/i,
  /\[WHITE-LABEL SCOPE GUARD\]/i,
  /BEGIN UNTRUSTED THIRD-PARTY CONTENT/i,
  /you are the assistant for/i,
  /system prompt/i,
];

/** Returns true if the model output appears to leak internal instructions. */
export function looksLikePromptLeak(output: string): boolean {
  return LEAK_SIGNATURES.some((re) => re.test(output));
}

/* ---------------------------------------------------------------- *
 * 3. Fail-closed HTML allowlist
 * ---------------------------------------------------------------- */

export interface SanitizeResult {
  html: string;
  /** Non-empty => the validator should FAIL CLOSED (repair or flag). */
  violations: string[];
}

/**
 * Strip dangerous markup. Anything risky that *cannot* be safely removed is
 * recorded as a violation so the caller fails closed rather than serving it.
 */
export function sanitizeHtml(input: string, opts: { sameHost: string }): SanitizeResult {
  const violations: string[] = [];
  let html = input;

  // Remove inline event handlers (onClick=, onerror=, ...), except a known
  // safe form submit handled elsewhere.
  html = html.replace(/\son[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, (m) => {
    if (/onsubmit/i.test(m)) return m; // allowlisted, validated separately
    violations.push("inline-event-handler");
    return "";
  });

  // Remove javascript: URLs.
  if (/javascript:/i.test(html)) {
    violations.push("javascript-url");
    html = html.replace(/javascript:/gi, "");
  }

  // Remove <iframe> entirely.
  if (/<iframe/i.test(html)) {
    violations.push("iframe");
    html = html.replace(/<iframe[\s\S]*?<\/iframe>/gi, "");
  }

  // Scripts: allow ONLY JSON-LD structured data and a same-host widget src.
  html = html.replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi, (full, attrs) => {
    const isJsonLd = /type\s*=\s*["']application\/ld\+json["']/i.test(attrs);
    const srcMatch = /src\s*=\s*["']([^"']+)["']/i.exec(attrs);
    const isSameHostWidget = srcMatch ? srcMatch[1].includes(opts.sameHost) : false;
    if (isJsonLd || isSameHostWidget) return full; // allowlisted
    violations.push("script");
    return "";
  });

  return { html, violations };
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
